### ISSUE TITLE
Add OBO file for error classes

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/arc-validate#30]
We want to standardize our error messages. To do so, an OBO-based ontology would be useful. This ontology should inhabit all errors, structured into classes, that we use and link them via relations.

**Comment by kMutagene** [comment]
This is also part of the API re-write for v2.

**Comment by kMutagene** [comment]
Moved out of this repo and milestone into https://github.com/CSBiology/OBO.NET/pull/32
