### ISSUE TITLE
Replace CvContainer-dependent parsing with mere CvParam parsing of ARC metadata

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/arc-validate#31]
Atm., metadata files are parsed via [ArcGraphModel.IO](https://github.com/nfdi4plants/ArcGraphModel)s parsing functions. Yet, we use those that return ICvBase lists consisting of CvParams and CvParams that are already aggregated into CvContainers. 
These aggregations hinder flat CvParam evaluation and overcomplicate the information extraction much more than necessary. Therefore, it may be best to use [shortly implemented parsing functions that only return mere CvParams](https://github.com/nfdi4plants/ArcGraphModel/issues/16).

**Comment by kMutagene** [comment]
This is now possible due to developments in [ARCTokenization](https://github.com/ARCTokenization), but since this requires a huge re-write of the core API, i move this to the 2.0.0 milestone. This should be implemented on the v2 branch.
