### ISSUE TITLE
Checking 16-digit ORCID identifier

### ISSUE THREAD

**Issue by Zerskk** [nfdi4plants/arc-validate#32]
@omaus, @kMutagene 

the Orcid identifier must correspond to the following scheme: xxxx-xxxx-xxxx-xxxx. Otherwise, no valid record can be created in Invenio. This must be checked, otherwise Archigator will create a "broken" Invenio record. 

The current example is the ARCInvenioTesting repository, where "orcid1", "orcid2" etc. are entered as identifiers in the isa file. The creation of an Invenio record fails here.

**Comment by omaus** [comment]
I will update the validation case for this, looking for such a scheme. 👍

**Comment by Zerskk** [comment]
Apparently, Invenio also calculates the checksums and checks whether it is a valid one.

ORCID scheme calculation:
[ORCID Scheme](https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier)

**Comment by omaus** [comment]
> Apparently, Invenio also calculates the checksums and checks whether it is a valid one.
> 
> ORCID scheme calculation: [ORCID Scheme](https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier)

😂😂

Ok, will implement that too.
