### ISSUE TITLE
Email address must be in correct format

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/arc-validate#35]
Atm., the pipeline only looks for persons with present email addresses but since Invenio cannot parse emails in incorrect formats (e.g. "myName[at]server.domain") or text that is no email at all, we must implement a check for valid email format (i.e. "<string>@<string>.<string>")

CC: @Zerskk

**Comment by kMutagene** [comment]
is this still relevant @omaus?

**Comment by omaus** [comment]
To me, this looks fixed... @kMutagene 

https://github.com/nfdi4plants/arc-validate/blob/18133bd2c55864c915b3743219881ad87db4051d/src/ARCExpect/StringValidationPattern.fs#L10
