### ISSUE TITLE
[Support] Pipeline not generating any output

### ISSUE THREAD

**Issue by ghost** [nfdi4plants/arc-validate#85]
This is more of a support request than an actual Issue, but I hope you can point me into the right direction.
I'm interested in incorporating the arc-validate pipeline into the arc-manager and re-use this for the Plantmicrobe project. Therefore I wanted to test your pipeline locally, but I'm facing some issues.
 
I pulled the latest docker image from the repo and started the docker container locally. Then I copied [this data](https://gitlab.plantmicrobe.de/trr-i01/inocybe_woglindeana_for_testing) inside the container and executed the `arc-validate validate` command on it. But no xml file or badge is generated and there's also no error message. In an earlier version, where I had to build the image from source it worked this way and I was able to generate a badge for the same example data.

**Comment by kMutagene** [comment]
Hi @awellmann ,

The new version of `arc-validate` works with target-based validation packages.

What previously was the default target is now the `invenio` package. The reason for this is that the initial scope of `arc-validate` was only validating whether an arc is 'publishable' . Now, `invenio` is just one of potentially many validation packages.

You can read more about this on the current draft branch of the [ARC specification v2](https://github.com/nfdi4plants/ARC-specification/blob/v2.0.0/ARC%20specification.md#mechanisms-for-arc-quality-control)

To use the `invenio` package in our container, you will first have to install it and then execute it:

```
arc-validate package install invenio
arc-validate validate -p invenio
```

Docs for the command line flags are available [here](https://nfdi4plants.github.io/arc-validate/arc-validate/introduction.html)

We are working on specification validation in parallel with developing the 2.0.0 version of the ARC specification. Once that version is finished and released, we aim to additionally provide specification validation as a default target for `arc-validate validate` (without package target)

**Comment by awellmann** [comment]
Oh I forgot to mention that I tried the package approach after the other one didn't work. But for some reason I ignored the invenio package and only used test. Now it works, thanks a lot! You can close it now I guess ;)
